def scim():
    return dict(env="AbcCont-TC-SCIM-v0",
                gamma=0.99,
                lamda=0.95,
                updates=100,
                epochs=80,
                worker_steps=20_000,
                action_std=0.5,
                n_mini_batch=6,
                value_loss_coefficient=0.5,
                hidden_layer_size=64,
                recurrence=dict(sequence_len=100,
                                hidden_state_size=64,
                                layer_type="lstm",
                                reset_hidden_state=True,
                                ),
                learning_rate_schedule=dict(initial=3e-5,
                                            final=3e-6,
                                            power=1,
                                            max_decay_steps=100,
                                            ),
                beta_schedule=dict(initial=0.0001,
                                   final=0.0001,
                                   power=1,
                                   max_decay_steps=100,
                                   ),
                clip_range_schedule=dict(initial=0.2,
                                         final=0.2,
                                         power=1,
                                         max_decay_steps=100,
                                         ),
                )


